title: Portfolio of Nicolas Kijak, Programmer
description: > # this means to ignore newlines until "baseurl:"
  Nicolas Kijak's programming portfolio and thoughts on professional programming
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
future: true

# Author Settings
author: Nicolas Kijak
author-img: nkijak.jpg # add your photo
about-author: Polyglot, Full Stack, Data, all the fun things in between for 15+ years
social-twitter: nkijak
social-github: nkijak 
social-linkedin: nkijak
social-email: nkijak.at.gmail
social-facebook: false

# Disqus
discus-identifier: nkijak-github-io

# Tracker
analytics: "UA-148188310-1" # Google Analytics

# Build Settings
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
